apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: hello_world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello_world
  template:
    metadata:
      labels:
        app: hello_world
    spec:
      containers:
      - name: nginx
        image: menzy_007:21
        ports:
        - containerPort: 80
